import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import { Container, Main, StyledLine, StyledTitle } from '../components/sharedstyles'
import styled from 'styled-components'
import Link from 'next/link'

export default function Buildings() {
  let mockBuildingsData = {
    Manufacturers: [
      {
        slug: "constructor",
        name: "Constructor"
      },
      {
        slug: "assembler",
        name: "Assembler"
      },
      {
        slug: "manufacturer",
        name: "Manufacturer"
      },
      {
        slug: "packager",
        name: "Packager"
      },
      {
        slug: "refinery",
        name: "Refinery"
      },
      {
        slug: "blender",
        name: "Blender"
      },
      {
        slug: "particle-accelerator",
        name: "Particle Accelerator"
      }
    ],
    Smelters: [
      {
        slug: "smelter",
        name: "Smelter"
      },
      {
        slug: "foundry",
        name: "Foundry"
      }
    ],
    Miners: [
      {
        slug: "miner-mk-1",
        name: "Miner Mk.1"
      },
      {
        slug: "miner-mk-1",
        name: "Miner Mk.2"
      },
      {
        slug: "miner-mk-1",
        name: "Miner Mk.3"
      }
    ],
    FluidExtractors: [
      {
        slug: "water-extractor",
        name: "Water Extractor"
      },
      {
        slug: "oil-extractor",
        name: "Oil Extractor"
      }
    ]
  }

  console.log('entries', Object.entries(mockBuildingsData))

  mockBuildingsData = Object.entries(mockBuildingsData)

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledHeaderSection>
          <StyledTitle>Buildings</StyledTitle>
          <StyledLine color='#E5AF07' />
          <StyledCategoiresContainer>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
            <StyledCategory></StyledCategory>
          </StyledCategoiresContainer>
          <StyledLine color='#E5AF07' />
        </StyledHeaderSection>
        <StyledBuildingsSection>
          {mockBuildingsData.map((e, i) => {
            return (
              <StyledBuildingsContainer hasTooManyBuildings={!(e[1].length <= 6)}>
              <StyledCategoryTitle>{i + 1}. {e[0]}</StyledCategoryTitle>
                {e[1].map((j) => {
                  return (
                    <StyledBuilding key={j.slug}>
                      <StyledBuildingImage name={j.slug} />
                      <StyledBuildingName>{j.name}</StyledBuildingName>
                    </StyledBuilding>
                  )
                })}
              </StyledBuildingsContainer>
            )
          })}
        </StyledBuildingsSection>
      </Main>

      <Footer />
    </Container>
  )
}

const StyledHeaderSection = styled.section`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 80%;
`

const StyledCategoiresContainer = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
`

const StyledCategory = styled.div`
  height: 120px;
  aspect-ratio: 1 / 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: ${props => props.primary ? "#D79845" : "#43454B"};
  margin: 0.5rem 0.25rem;
`

const StyledBuildingsSection = styled.section`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 80%;
  background-color: #131416;
  margin-top: 2rem;
  padding: 2rem;
`

const StyledBuildingsContainer = styled.div`
  width: 100%;
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  align-items: center;
  flex-wrap: wrap;
  margin-bottom: 4rem;
`

const StyledCategoryTitle = styled.div`
  width: 100%;
  height: 2rem;
  grid-column: 1 / 7;
  display: flex;
  align-items: center;
  background-color: #43454B;
  color: white;
  padding-left: 1rem;
  margin-bottom: 1rem;
  grid-gap: 3rem;
  font-size: 1.25rem;
`

const StyledBuilding = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem;
`

const StyledBuildingImage = styled.div`
  height: 180px;
  aspect-ratio: 1 / 1;
  background-color: #43454B;
  background-image: url(${props => 'https://u6.satisfactorytools.com/assets/images/items/' + props.name + '_256.png'});
  background-size: 90%;
  background-position: center;
  background-repeat: no-repeat;
`

const StyledBuildingName = styled.div`
  width: 180px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #43454B;
  color: white;
  padding: 1rem 0;
  margin-top: 0.05rem;
`