import Head from 'next/head'
import Footer from '../components/footer'
import Header from '../components/header'
import { Container, Main } from '../components/sharedstyles'
import styled from 'styled-components'
import Link from 'next/link'

import bannerImg from '/public/images/banner.jpeg'
import itemsBg from '/public/images/items-bg.jpg'
import buildingBg from '/public/images/buildings-bg.jpg'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledBannerSection>
          <StyledBanner image={bannerImg} />
          <StyledBannerText>
            Improve your production line
          </StyledBannerText>
        </StyledBannerSection>
        <StyledNavSection>
          <Link href="/items">
            <StyledNavItem>
              <StyledNavImage image={itemsBg} />
              <StyledNavText>Items</StyledNavText>
            </StyledNavItem>
          </Link>
          <StyledNavItem>
            <StyledNavImage image={buildingBg} />
            <StyledNavText>Buildings</StyledNavText>
          </StyledNavItem>
        </StyledNavSection>
      </Main>

      <Footer />
    </Container>
  )
}

const StyledBannerSection = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 48px;
  height: 50%;
  width: 100%;
`

const StyledBanner = styled.div`
  height: 40vh;
  width: 80%;
  background-image: url(${props => props.image.src});
  background-position: center;
  background-size: cover;
  border-radius: 16px;
  background-color: #141518;
`

const StyledBannerText = styled.div`
  height: 10vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 0.25rem 2rem ;
  background-color: #43454B;
  margin-top: -48px;
  border-width: 2px;
  border-radius: 1rem;
  border-color: #F2C800;
  border-style: solid;
  text-align: center;
  color: white;
  font-size: 2.5rem;
`

const StyledNavSection = styled.nav`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-around;
  width: 100%;
  height: 75vh;
  background-color: #141518;
  margin-top: 64px;
  position: relative;
`

const StyledNavItem = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 36%;
  cursor: pointer;
`

const StyledNavImage = styled.div`
  height: 48vh;
  width: 100%;
  border-radius: 8px;
  background-image: url(${(props) => props.image.src});
  background-size: cover;
  background-position: center;
  opacity: 0.8;
  background-color: #141518;
`

const StyledNavText = styled.div({
  height: "8vh",
  width: '50%',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: -32,
  backgroundColor: '#43454B',
  borderWidth: 3,
  borderRadius: 8,
  borderColor: "#F2C800",
  borderStyle: 'solid',
  textAlign: 'center',
  verticalAlign: 'center',
  color: 'white',
  fontSize: 32,
  zIndex: 1
})