import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import { Container, Main } from '../components/sharedstyles'
import styled from 'styled-components'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledBannerSection>
          <Image src="/images/banner.jpeg" alt="me" layout='fill' />
          <StyledBannerText>
            Improve your production line
          </StyledBannerText>
        </StyledBannerSection>
      </Main>

      <Footer />
    </Container>
  )
}

const StyledBannerSection = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 64;
  height: 50%;
  width: 100%;
  position: relative;
`

const StyledBanner = styled.div`
  height: 40vh;
  width: 80%;
  background-image: url(./banner.jpeg);
  background-position: center;
  background-size: cover;
  border-radius: 16px;
`

const StyledBannerText = styled.div`
  height: 10vh;
  width: 50%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-top: 8;
  background-color: #43454B;
  margin-top: -64;
  border-width: 2;
  border-radius: 24;
  border-color: #F2C800;
  border-style: solid;
  text-align: center;
  color: white;
  font-size: 42;
`

const StyledNavSection = styled.nav`
  display:'flex';
  flex-direction: 'row';
  align-items: 'center';
  justify-content: 'space-around';
  width: '100%';
  height: '75vh';
  background-color: '#141518';
  margin-top: 64;
  position: 'relative';
`

const StyledNavItem = styled.div({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  width: '36%',
  cursor: 'pointer'
})

const StyledNavImage = styled(Image)`
  height: 48vh;
  width: 100%;
  border-radius: 8px;
  background-image: url(${(props)=>props.imgUrl});
  background-size: cover;
  background-position: center;
  opacity: 0.8;
`

const StyledNavText = styled.div({
  height: "8vh",
  width: '50%',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: -32,
  backgroundColor: '#43454B',
  borderWidth: 3,
  borderRadius: 8,
  borderColor: "#F2C800",
  borderStyle: 'solid',
  textAlign: 'center',
  verticalAlign: 'center',
  color: 'white',
  fontSize: 32,
  zIndex: 1
})