import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import { Container, Main, StyledLine } from '../components/sharedstyles'
import styled from 'styled-components'

export default function items() {
  const mockData = [{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    },{
      name: 'Adaptive Control Unit'
    },{
      name: 'AI Limiter'
    }]

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledContainer>
          <StyledText>Items</StyledText>
          <StyledLine color='#E5AF07' />
          <StyledItemsContainer>
            {mockData.map((e, i) => {
              return (
                <StyledItem key={i}>
                  <StyledItemImage />
                  <StyledItemName>
                    {e.name}
                  </StyledItemName>
                </StyledItem>
              )
            })}
          </StyledItemsContainer>
        </StyledContainer>
      </Main>

      <Footer />
    </Container>
  )
}

const StyledContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 90%;
`

const StyledText = styled.div`
  width: 100%;
  text-align: left;
  padding: 1rem 1.5rem;
  color: white;
  font-size: 2.5rem;
  font-family: Roboto, sans-serif;
  font-weight: 400;
`

const StyledItemsContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, auto);
  gap: 1rem;
  align-items: center;
  justify-content: center;
  width: 100%;
  margin-top: 1rem;
`

const StyledItem = styled.div`
  width: 10vw;
  height: 13vw;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`

const StyledItemImage = styled.div`
  width: 100%;
  height: 10vw;
  background-color: #9BA3A9;
  background-image: url('/images/Adaptive_Control_Unit.png');
  background-position: center;
  background-size: cover;
`

const StyledItemName = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 3vw;
  background-color: #43454B;
  padding: 0.25rem;
  color: white;
  text-align: center;
`