import Head from 'next/head'
import Header from '../../../components/header'
import Footer from '../../../components/footer'
import styled from 'styled-components'
import { Container, Main, StyledLine, StyledTitle } from '../../../components/sharedstyles'
import { useRouter } from 'next/router'
import { getBuildableByName } from '../../../lib/api'
import Link from 'next/link'
import { useState } from 'react'

export default function Building({ buildable }) {
  const router = useRouter()
  const { category } = router.query

  const [clockspeed, setClockspeed] = useState(100)
  let energyConsumption = (buildable.meta?.powerInfo?.consumption * (clockspeed / 100) ** buildable.meta?.overclockInfo?.exponent).toFixed(3)

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledTitleSection>
          <StyledTitle>{category.charAt(0).toUpperCase() + category.slice(1)}</StyledTitle>
          <StyledLine color='#E5AF07' />
        </StyledTitleSection>
        <StyledContainer>
          <StyledDetailContainer>
            <StyledImage name={buildable.slug} />
            <StyledDetail>
              <StyledName>{buildable.name}</StyledName>
              <StyledCostTitle>Cost :</StyledCostTitle>
              <StyledCostContainer>
                {buildable.cost.map((e) => {
                  return (
                    <StyledCostItem key={e.itemClass}>
                      <StyledText>{e.quantity}x</StyledText>
                      <Link href={`/items/${e.itemClass}`}>
                        <StyledCostItemImage item={e.itemClass} />
                      </Link>
                    </StyledCostItem>
                  )
                })}
              </StyledCostContainer>
            </StyledDetail>
            <StyledDetail description>
              {buildable.description}
            </StyledDetail>
          </StyledDetailContainer>
          {
            buildable.isOverclockable &&
            <StyledConsumptionContainer>
              <StyledEnergyContainer>
                <div>{clockspeed}%</div>
                <StyledVerticalLine />
                <div>{parseFloat(energyConsumption)}MW</div>
              </StyledEnergyContainer>
              <StyledClockspeedContainer>
                <StyledClockspeedInput
                  type="range"
                  min={1}
                  max={250}
                  step={1}
                  onChange={e => { setClockspeed(e.currentTarget.value); }}
                  value={clockspeed}
                />
                <StyledClockspeedTextContainer>
                  <StyledClockspeedText overclocked={100 <= clockspeed} onClick={() => setClockspeed(100)}>100%</StyledClockspeedText>
                  <StyledClockspeedText overclocked={150 <= clockspeed} onClick={() => setClockspeed(150)}>150%</StyledClockspeedText>
                  <StyledClockspeedText overclocked={200 <= clockspeed} onClick={() => setClockspeed(200)}>200%</StyledClockspeedText>
                  <StyledClockspeedText overclocked={250 <= clockspeed} onClick={() => setClockspeed(250)}>250%</StyledClockspeedText>
                </StyledClockspeedTextContainer>
              </StyledClockspeedContainer>
            </StyledConsumptionContainer>
          }

        </StyledContainer>
      </Main>

      <Footer />
    </Container>
  )
}

export function getServerSideProps(context) {
  const name = context.query.building
  const buildable = getBuildableByName(name)

  return {
    props: { buildable }
  }
}

const StyledTitleSection = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 80%;
`

const StyledContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 80%;
  background-color: #131416;
  margin-top: 1rem;
  padding: 1.5rem;
`

const StyledDetailContainer = styled.section`
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 100%;
  height: 250px;
`

const StyledImage = styled.div`
  height: 100%;
  aspect-ratio: 1 / 1;
  background-color: #9BA3A9;
  background-image: url(${props => 'https://u6.satisfactorytools.com/assets/images/items/' + props.name + '_256.png'});
  background-position: center;
  background-size: 96%;
  background-repeat: no-repeat;
`

const StyledDetail = styled.div`
  height: 100%;
  width: calc(50% - 125px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: #202125;
  text-align: center;
  color: white;
  font-size: ${props => props.description ? '1rem' : '1.5rem'};
  ${props => props.description && 'padding: 2rem;'}
`

const StyledName = styled.div`
  width: 100%;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: 101010;
  color: white;
  text-align: center;
  font-size: 2rem;
`

const StyledCostTitle = styled.div`
  width: 100%;
  height: 30px;
  color: white;
  background-color: #D79845;
  text-align: left;
  padding-left: 2rem;
`

const StyledCostContainer = styled.div`
  width: 100%;
  height: 150px;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  background-color: #46484E;
`

const StyledCostItem = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  margin: 0 0.5rem;
`

const StyledText = styled.p`
  margin: 0;
`

const StyledCostItemImage = styled.div`
  width: 60px;
  aspect-ratio: 1 / 1;
  background-color: #202125;
  background-image: url(${props => 'https://u6.satisfactorytools.com/assets/images/items/' + props.item + '_256.png'});
  background-position: center;
  background-size: 96%;
  background-repeat: no-repeat;
  border-radius: 0.5rem;
  margin: 0 0.25rem;
  cursor: pointer;
`

const StyledConsumptionContainer = styled.div`
  height: 75px;
  width: 100%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
`

const StyledEnergyContainer = styled.div`
  height: 100%;
  width: 250px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-evenly;
  background-color: #43454B;
  color: white;
  font-size: 1.5rem;
`

const StyledVerticalLine = styled.div`
  height: 100%;
  width: 2px;
  justify-self: center;
  background-color: #F1C700;
`

const StyledClockspeedContainer = styled.div`
  height: 100%;
  width: calc(100% - 250px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: #9BA3A9;
`

const StyledClockspeedInput = styled.input`
  -webkit-appearance: none;
  appearance: none;
  background: transparent;
  background-size: 50px;
  cursor: pointer;
  width: 79%;
  ::-webkit-slider-runnable-track {
    height: 30px;
    background-color: #43454B;
    background: linear-gradient(90deg, #E39744 0%, #F7DE50 100%);
  }
  ::-moz-range-track {
    height: 30px;
    background-color: #43454B;
    background: linear-gradient(90deg, #E39744 0%, #F7DE50 100%);
  }
  ::-webkit-slider-thumb {
     -webkit-appearance: none;
     appearance: none;
     background-color: #43454B;
     height: 30px;
     width: 2px;
  }
`

const StyledClockspeedTextContainer = styled.div`
  width: 79%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: end;
`

const StyledClockspeedText = styled.div`
  text-align: right;
  cursor: pointer;
  color: ${props => props.overclocked ? '#FFE9a5' : '#141518'};
  margin-left: 6rem;
`