import Head from 'next/head'
import Header from '../../components/header'
import Footer from '../../components/footer'
import { Container, Main, StyledLine, StyledTitle } from '../../components/sharedstyles'
import styled from "styled-components"
import { useRouter } from 'next/router'
import { getFilteredItemsByName } from '../../lib/api'
import Link from 'next/link'

export default function Search({ items }) {
  const sortedItems = Object.values(items).sort((a, b) => (a.name.toLowerCase() > b.name.toLowerCase()) ? 1 : ((b.name > a.name) ? -1 : 0))
  const router = useRouter()
  const { name } = router.query

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledContainer>
          <StyledTitle>Search results for : &quot;<StyledSpan>{name}</StyledSpan>&quot;</StyledTitle>
          <StyledLine color='#E5AF07' />
          {sortedItems.length == 0 ?
            <StyledText>Nothing found.</StyledText> :
            <StyledItemsContainer>
              {sortedItems.map((e, i) => {
                return (
              <Link href={`/items/${e.slug}`} key={i} >
                <StyledItem>
                  <StyledItemImage name={e.slug} />
                  <StyledItemName>
                    {e.name}
                  </StyledItemName>
                </StyledItem>
              </Link>
              )
              })}
            </StyledItemsContainer>
          }
        </StyledContainer>
      </Main>

      <Footer />
    </Container>
  )
}

export function getServerSideProps(context) {
  const name = context.query.name

  const items = getFilteredItemsByName(name)

  return {
    props: { items }
  }
}

const StyledContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 90%;
`
const StyledSpan = styled.span`
  color: #D79845;
`

const StyledText = styled.div`
  width: 100%;
  height: 50vh;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 1.5rem;
`

const StyledItemsContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, auto);
  gap: 1rem;
  align-items: center;
  justify-content: center;
  width: 100%;
  margin-top: 1rem;
`


const StyledItem = styled.div`
  width: 10vw;
  height: 13vw;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  cursor: pointer;
`

const StyledItemImage = styled.div`
  width: 100%;
  height: 10vw;
  background-color: #9BA3A9;
  background-image: url(${props => 'https://u6.satisfactorytools.com/assets/images/items/' + props.name + '_256.png'});
  background-position: center;
  background-size: 90%;
  background-repeat: no-repeat;
`

const StyledItemName = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 3vw;
  background-color: #43454B;
  padding: 0.25rem;
  color: white;
  text-align: center;
`