import Head from 'next/head'
import Header from '../../components/header'
import Footer from '../../components/footer'
import styled from 'styled-components'
import { Container, Main, StyledLine } from '../../components/sharedstyles'
import { getItemByItemName } from '../../lib/api'
import Recipe from '../../components/sections/recipe'
import UsagesAsIngredient from '../../components/sections/usagesAsIngredient'


export default function Item({ item }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main>
        <StyledTitleSection>
          <StyledTitle>Item</StyledTitle>
          <StyledLine color='#E5AF07' />
        </StyledTitleSection>
        <StyledContainer>
          <StyledDetailContainer>
            <StyledImage name={item.slug} />
            <StyledDetail>
              <StyledName>{item.name}</StyledName>
              <StyledText>
                <p>Stack Size:</p>
                <p>{item.stackSize}</p>
              </StyledText>
              <StyledText primary>
                <p>Sink Value:</p>
                <p>{item.sinkPoints}</p>
              </StyledText>
              <StyledText>
                <p>Radioactive:</p>
                <p>{item.isRadioactive ? 'Yes' : 'No'}</p>
              </StyledText>
            </StyledDetail>
            <StyledDetail description>
              {item.description}
            </StyledDetail>
          </StyledDetailContainer>
          <Recipe />
          <UsagesAsIngredient />
        </StyledContainer>
      </Main>

      <Footer />
    </Container>
  )
}

export async function getServerSideProps(context) {
  var name = context.query.name
  const item = getItemByItemName(name)
  console.log('item is here!@! ->', item)
  return {
    props: { item }
  }
}

const StyledTitleSection = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 80%;
`

const StyledTitle = styled.div`
  width: 100%;
  text-align: left;
  padding: 1rem 1.5rem;
  color: white;
  font-size: 2.5rem;
  font-family: Roboto, sans-serif;
  font-weight: 400;
`

const StyledContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 80%;
  background-color: #131416;
  margin-top: 1rem;
  padding: 1.5rem;
`

const StyledDetailContainer = styled.section`
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 100%;
  height: 250px;
  margin-bottom: 2.5rem;
`

const StyledImage = styled.div`
  height: 100%;
  aspect-ratio: 1 / 1;
  background-color: #9BA3A9;
  background-image: url(${props => 'https://u6.satisfactorytools.com/assets/images/items/' + props.name + '_256.png'});
  background-position: center;
  background-size: 96%;
  background-repeat: no-repeat;
`

const StyledDetail = styled.div`
  height: 100%;
  width: calc(50% - 125px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: #202125;
  text-align: center;
  color: white;
  font-size: 1.5rem;
  ${props => props.description && 'padding: 2rem;'}
`

const StyledName = styled.div`
  width: 100%;
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: 101010;
  color: white;
  text-align: center;
  font-size: 2rem;
`

const StyledText = styled.div`
  width: 100%;
  height: 60px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  padding: 0 1rem;
  text-align: center;
  color: white;
  background-color: ${props => props.primary ? '#43454B' : '#46484E'};
`